### ISSUE TITLE
npm run dev is not working.

### ISSUE THREAD

**Issue by mandadimuralidharreddy** [derekbar90/catalyst#104]
Hi,
This is a great project.Thank you for sharing.
How do I run this project for development.
npm run dev  mentioned in readme file but not recognized as command because in root folder package.json its not exists.

**Comment by derekbar90** [comment]
@mandadimuralidharreddy Thanks for your interest! The entire setup is run via Docker and Docker Compose. I would look at the Makefile and use those commands which I've had others use with great success. If you still have issues, let me know!
